# Generated by Django 3.2.25 on 2024-08-02 17:41

import apps.web.files_path
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulaire_contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('no_formulaire', models.IntegerField()),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('courriel', models.EmailField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('sujet', models.CharField(max_length=100)),
                ('read', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagesWeb',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('url', models.ImageField(upload_to=apps.web.files_path.web_images_path)),
            ],
            options={
                'verbose_name': 'web_images',
                'db_table': 'web_images',
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(choices=[('sold_price', 'Average sold price'), ('days', 'Average days On market'), ('number_transactions', 'Number days Of transactions')], max_length=20)),
                ('initial_year', models.CharField(blank=True, max_length=4, null=True)),
                ('final_year', models.CharField(blank=True, max_length=4, null=True)),
                ('initial_value', models.CharField(blank=True, max_length=50, null=True)),
                ('final_value', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'web_statistics',
                'db_table': 'web_statistics',
            },
        ),
        migrations.CreateModel(
            name='VideosWeb',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tittle', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('videoId', models.CharField(max_length=100)),
                ('publishedAt', models.DateTimeField()),
                ('is_short', models.BooleanField(default=False)),
            ],
        ),
    ]
