# Generated by Django 4.2.11 on 2024-06-06 02:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulaire_contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('no_formulaire', models.IntegerField()),
                ('nom', models.CharField(max_length=100)),
                ('courriel', models.EmailField(max_length=100)),
                ('telephone', models.CharField(max_length=15)),
                ('message', models.TextField(blank=True, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('sujet', models.CharField(max_length=100)),
                ('read', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
