# Generated by Django 4.2.11 on 2024-06-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaire_contact',
            name='courriel',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formulaire_contact',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formulaire_contact',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
