# Generated by Django 3.2.25 on 2024-08-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesweb',
            name='type',
        ),
        migrations.AddField(
            model_name='imagesweb',
            name='reference',
            field=models.CharField(choices=[('sold_price', 'Average sold price'), ('days', 'Average days On market'), ('number_transactions', 'Number days Of transactions')], default='', max_length=30),
            preserve_default=False,
        ),
    ]
