# Generated by Django 4.2.11 on 2024-07-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_formulaire_contact_courriel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=50, null=True)),
                ('initial_year', models.CharField(blank=True, max_length=4, null=True)),
                ('final_year', models.CharField(blank=True, max_length=4, null=True)),
                ('initial_value', models.CharField(blank=True, max_length=50, null=True)),
                ('final_value', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
