# Generated by Django 4.2.11 on 2024-07-14 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_statistics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistics',
            old_name='subtitle',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='title',
        ),
    ]
