# Generated by Django 4.2.11 on 2024-07-25 02:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rename_subtitle_statistics_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesWeb',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('url', models.ImageField(upload_to='static/web/images/web_imgs/')),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
