# Generated by Django 3.2.25 on 2024-08-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20240802_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesweb',
            name='reference',
            field=models.CharField(choices=[('index_banner', '(Index) Banner'), ('index_donate_image', '(Index) Donate Image'), ('index_donate_background', '(Index) Donate Background'), ('index_team_background', '(Index) Team Background'), ('index_video_background', '(Index) Videos Background'), ('properties_banner', '(Properties) Banner'), ('team_banner', '(Team) Banner'), ('work_banner', '(Buying or Selling) Banner'), ('work_buy', '(Buying or Selling) Buy'), ('work_sell', '(Buying or Selling) Sell'), ('work_next_steps', '(Buying or Selling) Next Steps'), ('contact_banner', '(Contact) Banner'), ('contact_team_background', '(Contact) Team Background'), ('contact_team', '(Contact) Team'), ('videos_banner', '(Videos) Banner'), ('privacy_banner', '(Politic Privacy) Banner')], max_length=30),
        ),
    ]
