# Generated by Django 5.1.1 on 2024-12-22 19:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_imagesweb_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaDataWeb',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('meta_title_a', models.CharField(max_length=100, null=True)),
                ('meta_title_f', models.CharField(max_length=100, null=True)),
                ('meta_description_a', models.CharField(max_length=100, null=True)),
                ('meta_description_f', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'web_metadata',
                'db_table': 'web_metadata',
            },
        ),
    ]
