# Generated by Django 4.2.11 on 2024-07-31 02:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_imagesweb'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideosWeb',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tittle', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('videoId', models.CharField(max_length=100)),
                ('publishedAt', models.DateTimeField()),
            ],
        ),
    ]
