# Generated by Django 5.1.1 on 2024-12-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_metadataweb'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadataweb',
            name='origin',
            field=models.CharField(choices=[('index', 'Home'), ('properties', 'Properties'), ('sale', 'Properties Sale'), ('rent', 'Properties Rent'), ('team', 'Team'), ('buy', 'Buying'), ('sell', 'Selling'), ('video', 'Videos'), ('blog', 'Blog'), ('contact', 'Contact')], default='index', max_length=10),
        ),
    ]
