# Generated by Django 4.2.11 on 2024-07-31 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_videosweb'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosweb',
            name='is_short',
            field=models.BooleanField(default=False),
        ),
    ]
