# Generated by Django 5.1.1 on 2025-10-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_rename_meta_description_a_metadataweb_m_description_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadataweb',
            name='m_description_a',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='metadataweb',
            name='m_description_f',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='metadataweb',
            name='m_title_a',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='metadataweb',
            name='m_title_f',
            field=models.TextField(null=True),
        ),
    ]
