# Generated by Django 5.1.1 on 2026-02-22 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_metadataweb_m_description_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulaire_contact',
            name='tag',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
