# Generated by Django 5.1.1 on 2026-02-23 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_formulaire_contact_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaire_contact',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
