# Generated by Django 5.1.1 on 2026-02-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_formulaire_contact_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulaire_contact',
            name='broker',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formulaire_contact',
            name='buyer_rental',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='formulaire_contact',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
