# Generated by Django 5.1.1 on 2026-02-23 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_formulaire_contact_broker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulaire_contact',
            name='buyer_rental',
        ),
    ]
