# Generated by Django 5.1.1 on 2026-03-01 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_remove_formulaire_contact_buyer_rental'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulaire_contact',
            name='fub_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formulaire_contact',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formulaire_contact',
            name='sync_error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
