# Generated by Django 5.1.1 on 2026-03-01 02:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_formulaire_contact_fub_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulaire_contact',
            old_name='fub_id',
            new_name='person_fub_id',
        ),
        migrations.AddField(
            model_name='formulaire_contact',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
    ]
