# Generated by Django 5.1.1 on 2026-03-01 02:25

from django.db import migrations


def migrate_tag_to_tags(apps, schema_editor):
    FormulaireContact = apps.get_model("web", "Formulaire_contact")

    for obj in FormulaireContact.objects.all():
        if obj.tag:
            obj.tags = [obj.tag]
        else:
            obj.tags = []
        obj.save(update_fields=["tags"])

class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_rename_fub_id_formulaire_contact_person_fub_id_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_tag_to_tags),
    ]
