# Generated by Django 5.1.1 on 2026-03-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20260228_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulaire_contact',
            name='adresse_propriete',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formulaire_contact',
            name='no_inscription',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='formulaire_contact',
            name='url_inscription',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
