# Generated by Django 5.1.1 on 2026-03-06 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_formulaire_contact_adresse_propriete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulaire_contact',
            name='adresse_propriete',
        ),
    ]
