# Generated by Django 5.1.1 on 2026-08-24 16:08

from django.db import migrations, models


def comprobar_duplicados(apps, schema_editor):
    """Aborta con un mensaje util si el UNIQUE no va a poder crearse.

    Sin esto, un origin repetido hace fallar la migracion con un IntegrityError
    de Postgres que no dice cual es la fila sobrante ni como arreglarla.
    """
    MetaDataWeb = apps.get_model('web', 'MetaDataWeb')
    cuenta = {}
    for origen in MetaDataWeb.objects.values_list('origin', flat=True):
        cuenta[origen] = cuenta.get(origen, 0) + 1

    repetidos = sorted(origen for origen, veces in cuenta.items() if veces > 1)
    if repetidos:
        raise RuntimeError(
            'Hay metadatos web con el origin repetido (%s), asi que no se puede '
            'hacer unico el campo. Ejecuta antes:\n'
            '    python manage.py repair_metadata\n'
            'que lista las filas y dice como devolver la sobrante a su pagina.'
            % ', '.join(repetidos))


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_remove_formulaire_contact_adresse_propriete'),
    ]

    operations = [
        migrations.RunPython(comprobar_duplicados, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='metadataweb',
            name='origin',
            field=models.CharField(choices=[('index', 'Home'), ('properties', 'Properties'), ('sale', 'Properties Sale'), ('rent', 'Properties Rent'), ('team', 'Team'), ('buy', 'Buying'), ('sell', 'Selling'), ('video', 'Videos'), ('blog', 'Blog'), ('contact', 'Contact')], default='index', max_length=10, unique=True),
        ),
    ]
