# Generated by Django 4.2.11 on 2024-06-04 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_inscriptions_courtier_inscripteur_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptions',
            name='ind_vente_sans_garantie_legale',
            field=models.ForeignKey(blank=True, db_column='IND_VENTE_SANS_GARANTIE_LEGALE', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ind_vente_sans_garantie_legale', to='properties.valeursfixes'),
        ),
    ]
