# Generated by Django 4.2.11 on 2024-06-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_inscriptions_ind_vente_sans_garantie_legale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptions',
            name='ind_vente_sans_garantie_legale',
            field=models.CharField(blank=True, db_column='IND_VENTE_SANS_GARANTIE_LEGALE', max_length=1, null=True),
        ),
    ]
