# Generated by Django 3.2.25 on 2024-08-24 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_municipalites_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipalites',
            name='slug',
        ),
        migrations.AddField(
            model_name='municipalites',
            name='slug_anglaise',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='municipalites',
            name='slug_francaise',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
