# Generated by Django 4.2.11 on 2024-06-10 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_inscriptions_ind_vente_sans_garantie_legale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptions',
            name='categorie_propriete',
            field=models.ForeignKey(blank=True, db_column='CATEGORIE_PROPRIETE', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CATEGORIE_PROPRIETE', to='properties.valeursfixes'),
        ),
    ]
