# Generated by Django 3.2.25 on 2024-08-24 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20240823_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptions',
            name='mun_code',
            field=models.ForeignKey(db_column='MUN_CODE', on_delete=django.db.models.deletion.CASCADE, related_name='municipalite_code', to='properties.municipalites', to_field='code'),
        ),
    ]
