# Generated by Django 4.2.11 on 2024-06-10 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_inscriptions_categorie_propriete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptions',
            name='genre_propriete',
            field=models.ForeignKey(blank=True, db_column='GENRE_PROPRIETE', null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.genresproprietes', to_field='genre_propriete'),
        ),
    ]
