# Generated by Django 3.2.25 on 2024-08-24 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_inscriptions_mun_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='genresproprietes',
            name='slug_anglaise',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='genresproprietes',
            name='slug_francaise',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='inscriptions',
            name='genre_propriete',
            field=models.ForeignKey(blank=True, db_column='GENRE_PROPRIETE', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genre_proprietes', to='properties.genresproprietes', to_field='genre_propriete'),
        ),
    ]
