# Generated by Django 4.2.11 on 2024-07-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_inscriptions_genre_propriete'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptions',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
