# Generated by Django 5.1.1 on 2024-12-22 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_auto_20240824_0549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscriptions',
            options={},
        ),
    ]
