# Generated by Django 4.2.11 on 2024-07-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_inscriptions_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='membres',
            name='origin',
            field=models.CharField(default='Centris', max_length=10),
        ),
    ]
