# Generated by Django 5.1.1 on 2024-12-22 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_inscriptions_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscriptions',
            options={'ordering': ['devise_prix_demande', '-prix_demande', '-prix_location_demande']},
        ),
    ]
