# Generated by Django 3.2.25 on 2024-08-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='blog/images/default.png', null=True, upload_to='blog/images/'),
        ),
    ]
