# Generated by Django 3.2.25 on 2024-08-30 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ForeignKey(default="7166a36f-7d0d-4da6-a189-010d1225e7cd", on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser'),
            preserve_default=False,
        ),
    ]
