# Generated by Django 3.2.25 on 2024-08-30 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_article_authors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment',
        ),
    ]
