# Generated by Django 4.2.15 on 2024-08-31 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0010_rename_body_comment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='title_anglaise',
        ),
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.AddField(
            model_name='article',
            name='content_anglaise',
            field=django_ckeditor_5.fields.CKEditor5Field(default=1, verbose_name='ContentAnglaise'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='content_francaise',
            field=django_ckeditor_5.fields.CKEditor5Field(default=1, verbose_name='ContentFrancaise'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='title_francaise',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
