# Generated by Django 4.2.15 on 2024-09-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_rename_title_article_title_anglaise_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image',
            new_name='image_anglaise',
        ),
        migrations.RemoveField(
            model_name='article',
            name='intro',
        ),
        migrations.AddField(
            model_name='article',
            name='image_francaise',
            field=models.ImageField(blank=True, default='blog/images/default.png', null=True, upload_to='blog/images/'),
        ),
    ]
