# Generated by Django 4.2.15 on 2024-09-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_article_status_article_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='visites',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
