# Generated by Django 4.2.15 on 2024-09-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_article_likes_alter_like_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug_anglaise',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug_francaise',
            field=models.SlugField(unique=True),
        ),
    ]
