# Generated by Django 5.1.1 on 2026-02-27 10:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_rename_meta_description_a_article_m_description_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_hour',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
