# Generated by Django 5.1.1 on 2026-08-24 20:02

from django.db import migrations, models
from django.db.models import F


def repartir_fechas(apps, schema_editor):
    """Devuelve a date_hour su significado y estrena updated_at.

    La migracion 0026 anadio date_hour con default=timezone.now. Django aplica
    ese default a las filas que ya existen en el momento de migrar, asi que los
    144 articulos quedaron con el mismo instante: el dia en que se aplico en el
    servidor. Con date_hour pasando a ser la fecha de publicacion -- la que se
    muestra y por la que se ordena --, dejarlo asi haria que el blog entero
    apareciese fechado el mismo dia y que el orden quedase al azar.

    Se detecta ese sello por lo que es: un valor de date_hour compartido por
    mas de un articulo. Dos articulos publicados en el mismo segundo no pasa,
    y una fecha puesta a mano nunca coincide con otra. A esas filas se les
    pone su created_at, que es la unica fecha real que hay de cada una. Una
    fecha que alguien si haya escrito se queda como esta.

    updated_at se rellena con esa misma fecha en vez de con la del despliegue:
    no sabemos cuando se edito cada articulo por ultima vez, y su publicacion
    es la mejor aproximacion disponible. Se usa update() y no save() porque
    save() dispararia el auto_now y volveria a poner la fecha de hoy en todos,
    que es justo el problema que se esta arreglando.
    """
    Article = apps.get_model('blog', 'Article')

    repetidas = [
        fecha for fecha, veces in _cuenta(Article).items()
        if fecha is not None and veces > 1
    ]
    if repetidas:
        Article.objects.filter(date_hour__in=repetidas).update(date_hour=F('created_at'))

    Article.objects.filter(date_hour__isnull=True).update(date_hour=F('created_at'))
    Article.objects.update(updated_at=F('date_hour'))


def _cuenta(Article):
    cuenta = {}
    for fecha in Article.objects.values_list('date_hour', flat=True):
        cuenta[fecha] = cuenta.get(fecha, 0) + 1
    return cuenta


def deshacer(apps, schema_editor):
    """No se puede recuperar el sello uniforme, ni tiene sentido volver a el."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_article_date_hour_alter_article_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-date_hour', '-created_at')},
        ),
        migrations.AddField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.RunPython(repartir_fechas, deshacer),
    ]
