# Generated by Django 5.1.1 on 2026-10-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_alter_article_options_article_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='m_description_a',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='m_description_f',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
