# Generated by Django 3.2.25 on 2024-08-02 17:41

import apps.users.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametrization', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(default='profile_imgs/default.png', upload_to=apps.users.models.user_photo_directory_path)),
                ('image_over', models.ImageField(default='profile_imgs/default_over.png', upload_to=apps.users.models.user_photo_directory_path)),
                ('order', models.SmallIntegerField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, max_length=60, null=True)),
                ('occupation_anglaise', models.CharField(blank=True, max_length=60, null=True)),
                ('facebook', models.CharField(blank=True, max_length=60)),
                ('instagram', models.CharField(blank=True, max_length=60)),
                ('linkedin', models.CharField(blank=True, max_length=60)),
                ('twitter', models.CharField(blank=True, max_length=60)),
                ('tiktok', models.CharField(blank=True, max_length=60)),
                ('presentation_f', models.CharField(blank=True, max_length=2000, null=True)),
                ('presentation_a', models.CharField(blank=True, max_length=2000, null=True)),
                ('membre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.membres')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileTypeUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametrization.typeuser')),
            ],
            options={
                'verbose_name': 'profile_type_user',
                'db_table': 'profile_type_user',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='type_users', through='users.ProfileTypeUser', to='parametrization.TypeUser'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('modelo', models.CharField(max_length=100)),
                ('movimiento', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
