# Generated by Django 5.1.1 on 2024-09-16 05:13

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='public/app/profile_imgs/default.png', upload_to=apps.users.models.user_photo_directory_path),
        ),
         migrations.AlterField(
            model_name='profile',
            name='image_over',
            field=models.ImageField(default='public/app/profile_imgs/default_over.png', upload_to=apps.users.models.user_photo_directory_path),
        ),
    ]
