# Generated by Django 5.1.1 on 2024-12-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='meta_description_a',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='meta_description_f',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='meta_title_a',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='meta_title_f',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
