# Generated by Django 4.2.11 on 2024-05-15 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='static/media/default.png', upload_to='static/media/profile_imgs'),
        ),
    ]
