# Generated by Django 5.1.1 on 2026-02-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_meta_description_a_profile_m_description_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='occupation_anglaise',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
