# Generated by Django 3.2.25 on 2024-05-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_over',
            field=models.ImageField(default='static/media/default_over.png', upload_to='static/media/profile_imgs'),
        ),
    ]
