# Generated by Django 4.2.11 on 2024-05-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='occupation_anglaise',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
