# Generated by Django 4.2.11 on 2024-05-30 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_image_over'),
        ('users', '0009_profile_occupation_anglaise'),
    ]

    operations = [
    ]
