# Generated by Django 4.2.11 on 2024-07-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile_tiktok'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='presentation_a',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='presentation_f',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
