# Generated by Django 4.2.11 on 2024-07-24 10:43

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profile_presentation_a_profile_presentation_f'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_imgs/default.png', upload_to=apps.users.models.user_photo_directory_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_over',
            field=models.ImageField(default='profile_imgs/default_over.png', upload_to=apps.users.models.user_photo_directory_path),
        ),
    ]
