#!/usr/bin/env python
# -*- coding: utf-8 -*-


DICT_LABELS = {
    'en':{
        'web':{
            'index':{
                'header':{
                    'one':'LJ Realties | Your Trusted Real Estate Brokers | House, Condo for sale Sud Ouest, Ville-Marie',
                    'two':'House, Condo for sale Sud Ouest, Ville-Marie - LJ Immobilier Real estate broker',
                    'three':'Get your free property evaluation today!',
                },
                'title':{
                    'one':'unlock Your',
                    'two':'Dream home',
                    'three':'get a free buyers consulation',
                    'four': 'Your trusted real estate brokers',
                    'five': 'Discover your ',
                    'six': "Home's worth",
                },
                'sale':'For Sale',
                'rent':'For Rent',
                'button':{
                    'one':'Search',
                    'two':'Find a Broker',
                    'three':'Get Free Evaluation',
                    'four':'See More Properties',
                    'five':'Learn More',
                    'six':'Write a Review',
                    'seven':'See All Videos',
                    'eight':'Subscribe to our Newsletter',
                    'nine':'Subscribe',
                    'ten':'Free evaluation',
                    'eleven':'Free consultation',
                    'twelve':'Contact Us',
                },
                'placeholder':{
                    'one':'Search by city, neighbourhood, region, address or Centris No.',
                    'two':'Full name',
                    'three':'E-mail',
                    'four':'Phone',
                    'five':'Your E-mail',
                },
                'text': {
                    'one': 'Discover',
                    'two': 'Our statistics',
                    'three': 'Average sold price',
                    'four': 'Compared to listing price',
                    'five': 'Average days',
                    'six': 'On market',
                    'seven': 'Number days',
                    'eight': 'Of transactions',
                    'nine': 'days',
                    'ten': 'Meet',
                    'eleven': 'Our team',
                    'twelve': 'LJ Realties is a boutique agency that has been in operation since 2013.',
                    'twelve_b': 'What makes us different from the rest? We strive to be the real estate industry leader in the Greater Montreal Area by delivering unparalleled service, weaving transparency and integrity into each interaction, and adopting a progressive education-centric approach with both our clients and our team. This, mixed with our unprecedented work ethic, are just two reasons that help set us apart from our competitors.',
                    'thirteen': 'Popular Listings',
                    'fourteen': 'We donate to',
                    'fifteen': 'Autism montreal',
                    'sixteen': 'A percentage of our proceeds from each transaction goes towards Autism Montreal.',
                    'seventeen': 'We donated over $10,000 in 2023',
                    'eighteen': 'Autisme Montréal is a place that inspires, unites, carries hope, promotes growth and social solidarity.',
                    'nineteen': 'Our clients',
                    'twenty': 'testimonials',
                    'twenty_one': 'watch our',
                    'twenty_two': 'lasted videos',
                    'twenty_three': 'Our sold properties',
                    'twenty_four': 'Required fields',
                    'twenty_five': 'Privacy policy',
                    'twenty_six': 'All rights reserved, Columba Tecnology',
                    'twenty_seven': 'Cookie Notice',
                    'twenty_eight': 'We use cookies to give you the best possible experience on our website.',
                    'twenty_nine': 'By continuing to browse, you agree to our website’s use of cookies. To learn more',
                    'thirty': 'click here',
                    'thirty_one': 'Got it',
                    'thirty_two': 'As expert real state brokers, we deliver exceptional results.',
                    'thirty_three': 'Our average sold price is among the highest in the market, our listings sell faster, and we have completed numerous successful transactions.',
                    'thirty_four': 'Trust us for a seamless and profitable real estate experience.',
                }
            },
            'menu':{
                'name':{
                    'one':'Properties',
                    'two':'Our Team',
                    'three':'Buying or Selling',
                    'four':'Our Calculator',
                    'five':'Videos',
                    'six':'Blog',
                    'seven':'Contact',
                },
                'url':{
                    'one':'properties',
                    'two':'real-estate-broker',
                    'three':'work-with-us',
                    'four':'',
                    'five':'media',
                    'six':'https://blog.ljrealties.com/',
                    'seven':'contact-realestate-broker',
                    'eight':'https://41nbopg8umd.typeform.com/to/nT2BsAQ2',
                },
            },
            'properties':{
                'text': {
                    'one':'Display Mode',
                    'two':'List',
                    'three':'Mosaic',
                }
            },
            'videos':{
                'title':{
                    'one':'Our',
                    'two':'Videos',
                },
                'button':{
                    'one':'Watch Video',
                }
            },
            'contact':{
                'title':{
                    'one':'Reach out ',
                    'two':'Today',
                    'three':"Let's make your real estate dreams a reality!",
                },
                'button':{
                    'one':'Contact Us',
                    'two':'Book a call with us',
                },
                'text': {
                    'one':'Please fill out this form and ',
                    'two':'We will contact you as soon as possible',
                    'three':'First Name',
                    'four':'Last Name',
                    'five':'E-mail',
                    'six':'Phone',
                    'seven':'Comments',
                    'eight':'Required fields',
                    'nine':'Contact Info',
                    'ten':'Call us',
                    'eleven':'We are open from Monday to Friday',
                    'twelve':'Follow Us',
                    'thirteen':'Next',
                    'fourteen':'Steps',
                    'fifteen':"Buying or selling a home in a challenging market isn't easy, but with the right team you will save yourself time and money.",
                    'sixteen':'If you would like to go over specific opportunities, put together your game plan, and/or get answers to your questions.',
                    'seventeen':'The next step would be to set up a short buyer strategy call.',
                }
            },
            'privacy':{
                'title':{
                    'one':'Privacy',
                    'two':'Policy',
                },
                'url':'privacy-policy',
            },
            'team':{
                'title':{
                    'one':'Your Trusted',
                    'two':'Real Estate Brokers',
                    'three':'Meet Our Team',
                },
                'button':{
                    'one':'Read Bio',
                },
                'text': {
                    'one':'Founder & Certified Real Estate Broker',
                    'two':'Office Manager & Residential Real Estate Broker',
                    'three':'Residential Real Estate Broker',
                    'four':'Residential Real Estate Broker',
                    'five':'Marketing Manager',
                    'six':'Listing Coordinator',
                    'seven':'Transaction Coordinator',
                    'eight':'Search Real Estate Broker',
                }
            },
            'work':{
                'title':{
                    'one':'Work',
                    'two':'With Us',
                },
                'button':{
                    'one':'Download buyers booklet',
                    'two':'Download listing booklet',
                    'three':'Contact Us',
                    'four':'Download',
                    'five':'Submit',
                },
                'text': {
                    'one':'I Want To',
                    'two':'Buy',
                    'three':'I Want To',
                    'four':'Sell',
                    'five':'There are many steps involved in getting you from where you are to owning a new home. That’s where knowledge and experience come into play. Don’t worry, we will be there to guide you throughout the entire process and help find a property that meets your needs. This includes being present at all visits, advising you through the purchase negotiations, the pre-purchase inspection, as well as financing and finally, completing the purchase. All of these steps may seem overwhelming, but with our help, you will find yourself in your new home before you know it!',
                    'six':'Selling your home may seem like a daunting endeavour, but we are here to help you through the process. You can count on our team’s extensive knowledge of real estate and finance to assist with verifications, evaluations, marketing, and more.',
                    'seven':'Help Us Bring',
                    'eight':'Your real estate project to life',
                    'nine':'Please complete the form to display the download link',
                },
                'placeholder':{
                    'one':'Full name',
                    'two':'E-mail',
                    'three':'Phone',
                },
            },
        },
    },
    'fr':{
        'web':{
            'index':{
                'header':{
                    'one':'LJ Realties | Vos courtiers immobiliers de confiance | Maison, Condo à vendre Sud Ouest, Ville-Marie',
                    'two':"LJ Realties est votre courtier immobilier résidentiel dans le Sud Ouest, Ville-Marie. Nous avons une expertise et une expérience dans l'immobilier, pour l'achat ou la vente de maisons.",
                    'three':"Obtenez une évaluation gratuite de votre propriété dès aujourd'hui !",
                },
                'title':{
                    'one':"éverrouillez la maison",
                    'two':'de vos rêves',
                    'three':'Obtenez une consultation acheteurs gratuite',
                    'four': 'Vos courtiers immobiliers de confiance',
                    'five': 'Découvrez la valeur',
                    'six': 'de votre maison',
                },
                'sale':'À Vendre',
                'rent':'À Louer',
                'button':{
                    'one':'Rechercher',
                    'two':'Trouvez un Courtier',
                    'three':'Obtenir une évaluation Gratuite',
                    'four':'Voir Plus De Propriétés',
                    'five':'En Savoir Plus',
                    'six':'Laissez un Avis',
                    'seven':'Voir Toutes Les Vidéos',
                    'eight':"S'abonner À Notre Infolettre",
                    'nine':"S'abonner",
                    'ten':"évaluation gratuite",
                    'eleven':"Consultation gratuite",
                    'twelve':'Contactez-nous',
                },
                'placeholder':{
                    'one':'Recherche par ville, quartier, région, adresse ou No Centris.',
                    'two':'Nom Complet',
                    'three':'Courriel',
                    'four':'Téléphone',
                    'five':'Votre courriel',
                },
                'text': {
                    'one': 'Découvrir',
                    'two': 'Nos statistiques',
                    'three': 'Prix de vente moyen',
                    'four': 'Par Rapport AU Prix Demandé',
                    'five': 'Nombre de jours Moyens',
                    'six': 'Sur le marché',
                    'seven': 'Nombre',
                    'eight': 'De transactions',
                    'nine': 'jours',
                    'ten': 'Rencontrez',
                    'eleven': 'Notre équipe',
                    'twelve': 'LJ Immobilier est une agence qui est en service depuis 2013.',
                    'twelve_b': "Qu'est-ce qui nous différencie des autres? Nous nous efforçons d'être le chef de file de l'industrie immobilière dans la grande région de Montréal en offrant un service inégalé, en tissant la transparence et l'intégrité dans chaque interaction et en adoptant une approche progressive centrée sur l'éducation, tant avec nos clients qu'avec notre équipe. Ceci, associé à notre éthique de travail sans précédent, ne sont que deux des raisons qui nous aident à nous distinguer de nos concurrents.",
                    'thirteen': 'Les Propriétés Populaires',
                    'fourteen': 'Nous faisons don à',
                    'fifteen': 'Autisme Montréal',
                    'sixteen': 'Un pourcentage du produit de chaque transaction est versé à Autisme Montréal.',
                    'seventeen': 'Nous avons donné plus de 10 000 dollars en 2023',
                    'eighteen': "Autisme Montréal est un lieu qui inspire, rassemble, porte l'espoir, favorise l'épanouissement et la solidarité sociale.",
                    'nineteen': 'Les témoignages',
                    'twenty': 'De nos clients',
                    'twenty_one': 'Regarder notre',
                    'twenty_two': 'Dernières vidéos',
                    'twenty_three': 'Nos propriétés vendues',
                    'twenty_four': 'Champs obligatoires',
                    'twenty_five': 'Politique de confidentialité',
                    'twenty_six': 'Tous droits réservés, Columba Technology',
                    'twenty_seven': 'Avis sur les cookies',
                    'twenty_eight': 'Nous utilisons des cookies pour vous offrir la meilleure expérience possible sur notre site Web.',
                    'twenty_nine': "En continuant à naviguer, vous acceptez l'utilisation de cookies sur notre site Web. Pour en savoir plus",
                    'thirty': 'cliquez ici',
                    'thirty_one': "C'est compris",
                    'thirty_two': "En tant que courtiers experts en immobilier, nous fournissons des résultats exceptionnels.",
                    'thirty_three': "Notre prix de vente moyen est l'un des plus élevés du marché, nos biens se vendent plus rapidement et nous avons réalisé de nombreuses transactions avec succès.",
                    'thirty_four': "Trust us for a seamless and profitable real estate experience.",
                }
            },
            'menu':{
                'name':{
                    'one':'Propriétés',
                    'two':'Notre Équipe',
                    'three':'Acheter ou Vendre',
                    'four':'Notre Calculateur',
                    'five':'Vidéos',
                    'six':'Blogue',
                    'seven':'Contact',
                },
                'url':{
                    'one':'proprietes',
                    'two':'courtier-immobilier',
                    'three':'travailler-avec-nous',
                    'four':'',
                    'five':'media',
                    'six':'https://blog.ljrealties.com/',
                    'seven':'contact-courtier-immobilier',
                    'eight':'https://41nbopg8umd.typeform.com/to/k4c7H9i3',
                },
            },
            'properties':{
                'text': {
                    'one':"Mode d'affichage",
                    'two':'Liste',
                    'three':'Mosaïque',
                }
            },
            'videos':{
                'title':{
                    'one':'Nos',
                    'two':'Vidéos',
                },
                'button':{
                    'one':'Visionner',
                }
            },
            'contact':{
                'title':{
                    'one':'Contactez-',
                    'two':'Nous',
                    'three':'Réalisons vos rêves immobiliers !',
                },
                'button':{
                    'one':'Contactez-Nous',
                    'two':'Planifiez un appel avec nous',
                },
                'text': {
                    'one':'Veuillez remplir ce formulaire et',
                    'two':'Nous vous contacterons dès que possible',
                    'three':'Prénom',
                    'four':' Nom de famille',
                    'five':'Courriel',
                    'six':'Téléphone',
                    'seven':'Commentaires',
                    'eight':'Champs obligatoires',
                    'nine':'Informations de contact',
                    'ten':'Appelez-nous',
                    'eleven':'Nous sommes ouverts du lundi au vendredi',
                    'twelve':'Suivez-nous',
                    'thirteen': 'Suivant',
                    'fourteen': 'Étapes',
                    'fifteen': "Acheter ou vendre une maison sur un marché difficile n'est pas facile, mais avec la bonne équipe, vous gagnerez du temps et de l'argent.",
                    'sixteen': "Si vous souhaitez discuter d'opportunités spécifiques, élaborer votre plan d'action et/ou obtenir des réponses à vos questions.",
                    'seventeen': "La prochaine étape serait de planifier un court appel stratégique pour les acheteurs."
                }
            },
            'privacy':{
                'title':{
                    'one':'Politique',
                    'two':'De Confidentialité',
                },
                'url':'politique-confidentialite',
            },
            'team':{
                'title':{
                    'one':'Votre Confiance',
                    'two':'Courtiers en immobilier',
                    'three': 'Rencontrer notre équipe',
                },
                'button':{
                    'one':'Lire la Bio',
                },
                'text': {
                    'one':'Fondateur et courtier immobilier agréé DA',
                    'two':'Directrice de bureau et Courtier Immobilier Résidentiel',
                    'three':'Courtier Immobilier Résidentiel',
                    'four':'Courtier Immobilier Résidentiel',
                    'five':'Directrice du Marketing',
                    'six':'Coordonnatrice des inscriptionsr',
                    'seven':'Coordonnatrice des transactions',
                    'eight':'Recherche Courtier immobilier',
                }
            },
            'work':{
                'title':{
                    'one':'Travaillez',
                    'two':'Avec Nous',
                },
                'button':{
                    'one':"Télécharger la brochure de l'acheteur",
                    'two':'Télécharger la brochure du vendeur',
                    'three':'Contactez-nous',
                    'four':'Télécharger',
                    'five':'Soumettre',
                },
                'text': {
                    'one':'Je Veux',
                    'two':'Acheter',
                    'three':'Je veux',
                    'four':'Vendre',
                    'five':"Il y a de nombreuses étapes à franchir pour passer de votre situation actuelle à la possession d'une nouvelle maison. C'est là que les connaissances et l'expérience entrent en jeu. Ne vous inquiétez pas, nous serons là pour vous guider tout au long du processus et vous aider à trouver une propriété qui répond à vos besoins. Il s'agit notamment d'être présent lors de toutes les visites, de vous conseiller lors des négociations d'achat, de l'inspection préalable à l'achat, ainsi que du financement afin de conclure l'achat. Toutes ces étapes peuvent sembler insurmontables, mais avec notre aide, vous vous retrouverez dans votre nouvelle maison avant même de vous en rendre compte !",
                    'six':"La vente de votre maison peut sembler être un processus intimidant, mais nous sommes là pour vous aider dans ce processus. Vous pouvez compter sur les connaissances approfondies de notre équipe en matière d'immobilier et de finances, pour vous aider dans les vérifications, les évaluations, le marketing, etc.",
                    'seven':'Aidez-nous à donner',
                    'eight':'Vie à votre projet immobilier',
                    'nine':'Veuillez remplir le formulaire pour afficher le lien de téléchargement',
                },
                'placeholder':{
                    'one':'Nom et prénom',
                    'two':'Courriel',
                    'three':'Téléphone',
                },
            },
        },
    },
}
