#!/usr/bin/env python
# -*- coding: utf-8 -*-


DICT_LABELS = {
    'en':{
        'web':{
            'index':{
                'header':{
                    'one':'LJ Realties | Your Trusted Real Estate Brokers | House, Condo for sale Sud Ouest, Ville-Marie',
                    'two':'House, Condo for sale Sud Ouest, Ville-Marie - LJ Immobilier Real estate broker',
                    'three':'Get your free property evaluation today!',
                },
                'title':{
                    'one':'unlock Your',
                    'two':'Dream home',
                    'three':'get a free buyers consulation',
                    'four': 'Your trusted real estate brokers',
                    'five': 'Discover your ',
                    'six': "Home's worth",
                },
                'sale':'For Sale',
                'rent':'For Rent',
                'all':'All',
                'button':{
                    'one':'Search',
                    'two':'Find a Broker',
                    'three':'Get a Free Evaluation',
                    'four':'See More Properties',
                    'five':'Learn More',
                    'six':'Write a Review',
                    'seven':'See All Videos',
                    'eight':'Subscribe to our Newsletter',
                    'nine':'Subscribe',
                    'ten':'Free evaluation',
                    'eleven':'Free consultation',
                    'twelve':'Contact Us',
                    'thirteen':'Price',
                },
                'placeholder':{
                    'one':'Search by city, neighbourhood, region, address or Centris No.',
                    'two':'Full name',
                    'three':'E-mail',
                    'four':'Phone',
                    'five':'Your E-mail',
                    'six':'Your First Name',
                    'seven':'Your Last Name',
                },
                'text': {
                    'one': 'Discover',
                    'two': 'Our statistics',
                    'three': 'Average sold price',
                    'four': 'Compared to listing price',
                    'five': 'Average days',
                    'six': 'On market',
                    'seven': 'Number of',
                    'eight': 'transactions',
                    'nine': 'days',
                    'ten': 'Meet',
                    'eleven': 'Our team',
                    'twelve': 'LJ Realties is a boutique agency that has been in operation since 2013.',
                    'twelve_b': 'What makes us different from the rest? We strive to be the real estate industry leader in the Greater Montreal Area by delivering unparalleled service, weaving transparency and integrity into each interaction, and adopting a progressive education-centric approach with both our clients and our team. This, mixed with our unprecedented work ethic, are just two reasons that help set us apart from our competitors.',
                    'thirteen': 'Popular Listings',
                    'fourteen': 'We donate to',
                    'fifteen': 'Autism montreal',
                    'sixteen': 'A percentage of our proceeds from each transaction goes towards Autism Montreal.',
                    'seventeen': 'We donated over $10,000 in 2023',
                    'eighteen': 'Autisme Montréal is a place that inspires, unites, carries hope, promotes growth and social solidarity.',
                    'nineteen': 'Our clients',
                    'twenty': 'testimonials',
                    'twenty_one': 'watch our',
                    'twenty_two': 'lasted videos',
                    'twenty_three': 'Our sold properties',
                    'twenty_four': 'Required fields',
                    'twenty_five': 'Privacy policy',
                    'twenty_six': 'All rights reserved, Columba Tecnology',
                    'twenty_seven': 'Cookie Notice',
                    'twenty_eight': 'We use cookies to give you the best possible experience on our website.',
                    'twenty_nine': 'By continuing to browse, you agree to our website’s use of cookies. To learn more',
                    'thirty': 'click here',
                    'thirty_one': 'Got it',
                    'thirty_two': 'As expert real state brokers, we deliver exceptional results.',
                    'thirty_three': 'Our average sold price is among the highest in the market, our listings sell faster, and we have completed numerous thousands of successful transactions.',
                    'thirty_four': 'Trust us for a seamless and profitable real estate experience.',
                }
            },
            'menu':{
                'name':{
                    'one':'Properties',
                    'two':'Our Team',
                    'three':'Buying or Selling',
                    'four':'Our Calculator',
                    'five':'Videos',
                    'six':'Blog',
                    'seven':'Contact',
                },
                'url':{
                    'one':'properties',
                    'two':'real-estate-broker',
                    'three':'work-with-us',
                    'four':'',
                    'five':'media',
                    'six':'https://blog.ljrealties.com/',
                    'seven':'contact-realestate-broker',
                    'eight':'https://41nbopg8umd.typeform.com/to/nT2BsAQ2',
                },
            },
            'properties':{
                'text': {
                    'one':'Display Mode',
                    'two':'List',
                    'three':'Mosaic',
                }
            },
            'videos':{
                'title':{
                    'one':'Our',
                    'two':'Videos',
                    'three':'All',
                    'four':'Shorts',
                    'five':'Videos',
                },
                'button':{
                    'one':'Watch Video',
                }
            },
            'contact':{
                'title':{
                    'one':'Reach out ',
                    'two':'Today',
                    'three':"Let's make your real estate dreams a reality!",
                },
                'button':{
                    'one':'Contact Us',
                    'two':'Book a call with us',
                },
                'text': {
                    'one':'Please fill out this form and ',
                    'two':'We will contact you as soon as possible',
                    'three':'First Name',
                    'four':'Last Name',
                    'five':'E-mail',
                    'six':'Phone',
                    'seven':'Comments',
                    'eight':'Required fields',
                    'nine':'Contact Info',
                    'ten':'Call us',
                    'eleven':'We are open from Monday to Friday',
                    'twelve':'Follow Us',
                    'thirteen':'Next',
                    'fourteen':'Steps',
                    'fifteen':"Buying or selling a home in a challenging market isn't easy, but with the right team you will save yourself time and money.",
                    'sixteen':'If you would like to go over specific opportunities, put together your game plan, and/or get answers to your questions.',
                    'seventeen':'The next step would be to set up a short buyer strategy call.',
                }
            },
            'privacy':{
                'title':{
                    'one':'Privacy',
                    'two':'Policy',
                },
                'url':'privacy-policy',
            },
            'team':{
                'title':{
                    'one':'Your Trusted',
                    'two':'Real Estate Brokers',
                    'three':'Meet Our Team',
                },
                'button':{
                    'one':'Read Bio',
                },
                'text': {
                    'one':'Founder & Certified Real Estate Broker',
                    'two':'Office Manager & Residential Real Estate Broker',
                    'three':'Residential Real Estate Broker',
                    'four':'Residential Real Estate Broker',
                    'five':'Marketing Manager',
                    'six':'Listing Coordinator',
                    'seven':'Transaction Coordinator',
                    'eight':'Search Real Estate Broker',
                }
            },
            'work':{
                'title':{
                    'one':'Work',
                    'two':'With Us',
                    'three':'Buying or',
                    'four':'Selling',
                },
                'button':{
                    'one':'Download buyers booklet',
                    'two':'Download listing booklet',
                    'three':'Contact Us',
                    'four':'Download',
                    'five':'Submit',
                    'six':'Book a buyers consultation',
                    'seven':'Download our buyers guide',
                    'eight':'Get a free home evaluation',
                    'nine':'Download our sellers guide',
                    'ten':'Book a call with us',
                },
                'text': {
                    'one':'I Want',
                    'two':'To Buy',
                    'three':'I Want',
                    'four':'To Sell',
                    'five':'There are many steps involved in getting you from where you are to owning a new home.',
                    'six':'Selling your home may seem like a daunting endeavour, but we are here to help you through the process. Count on our team’s extensive knowledge of real estate and finance to ensure a smooth and successful sale.',
                    'seven':'Help Us Bring',
                    'eight':'Your real estate project to life',
                    'nine':'Please complete the form to display the download link',
                    'ten':'Our experience ensures your success',
                    'eleven':'That’s where knowledge and experience come into play.',
                    'twelve':'Don’t worry, we will be there to guide you throughout the entire process and help find a property that meets your needs.',
                    'thirteen':'This includes being present at all visits, advising you through the purchase negotiations, the pre-purchase inspection, as well as financing and finally, completing the purchase. All of these steps may seem overwhelming, but with our help, you will find yourself in your new home before you know it!',
                    'fourteen':'Accompanied visits',
                    'fifteen':'We will be present at all visits, ensuring you have expert guidance every step of the way.',
                    'sixteen':'Negotiation support',
                    'seventeen':'Our team will advise you through the purchase negotiations, helping you secure the best deal.',
                    'eighteen':'Pre-purchase inspection',
                    'nineteen':'We’ll assist you during the pre-purchase inspection to ensure your prospective home meets all your expectations',  
                    'twenty':'Financing assistance',
                    'twenty_one':'We provide support in securing financing, guiding you to the best options for your needs.', 
                    'twenty_two':'Completion of purchase',
                    'twenty_three':'Finally, we’ll be with you through the completion of the purchase, making sure everything goes smoothly.',
                    'twenty_four':'You can count on our team’s extensive knowledge of real estate and finance to assist with verifications, evaluations, marketing, and more.',
                    'twenty_five':'Initial Consultation',
                    'twenty_six':"Discuss your goals and assess your home's value.",
                    'twenty_seven':'Verification & Evaluation',
                    'twenty_eight':'Leverage our expertise for thorough verifications and accurate evaluations.',
                    'twenty_nine':'Marketing Strategy',
                    'thirty':'Develop and implement an effective marketing plan.',
                    'thirty_one':'Showings & Open Houses',
                    'thirty_two':'Organize and manage property viewings.',
                    'thirty_three':'Negotiations',
                    'thirty_four':'Guide you through offers and negotiations.',
                    'thirty_five':'Closing',
                    'thirty_six':'Assist with the final steps to complete the sale.',
                    'thirty_seven':'Next',
                    'thirty_eight':'Steps',
                    'thirty_nine':"Buying or selling a home in a challenging market isn't easy,", 
                    'forty':"but with the right team you will save yourself time and money.",
                    'forty_one':"If you would like to go over specific opportunities, put together your game plan, and/or get",
                    'forty_two':"answers to your questions - the next step would be to set up a short buyer strategy call.",
                },
                'placeholder':{
                    'one':'Full name',
                    'two':'E-mail',
                    'three':'Phone',
                },
            },
            'blog':{
                'button':{
                    'one':'Login',
                    'two':'Or',
                    'three':'Sign up',
                    'four':'Create an account',
                    'five':'Submit comment',
                },
                'placeholder':{
                    'one':'E-mail',
                    'two': 'Confirm E-mail',
                    'three': 'Password',
                    'four': 'Confirm Password',
                },
                'error':{
                    'one':'Emails do not match.',
                    'two': 'Passwords do not match.',
                    'three': 'The password must be at least 8 characters long, include letters, numbers and a special character.',
                    'four': 'The comment cannot be empty',
                },
                'text':{
                    'one':'Comments',
                }
            },
        },
    },
    'fr':{
        'web':{
            'index':{
                'header':{
                    'one':'LJ Realties | Vos courtiers immobiliers de confiance | Maison, Condo à vendre Sud Ouest, Ville-Marie',
                    'two':"LJ Realties est votre courtier immobilier résidentiel dans le Sud Ouest, Ville-Marie. Nous avons une expertise et une expérience dans l'immobilier, pour l'achat ou la vente de maisons.",
                    'three':"Obtenez une évaluation gratuite de votre propriété dès aujourd'hui !",
                },
                'title':{
                    'one':"Trouvez la maison",
                    'two':'de vos rêves',
                    'three':'Obtenez une consultation d’acheteurs gratuite',
                    'four': 'Vos courtiers immobiliers de confiance',
                    'five': 'Découvrez la valeur',
                    'six': 'de votre maison',
                },
                'sale':'À Vendre',
                'rent':'À Louer',
                'all':'Toutes',
                'button':{
                    'one':'Rechercher',
                    'two':'Trouvez un Courtier',
                    'three':'Obtenir une évaluation Gratuite',
                    'four':'Voir Plus De Propriétés',
                    'five':'En Savoir Plus',
                    'six':'Laissez un Avis',
                    'seven':'Voir Toutes Les Vidéos',
                    'eight':"S'abonner À Notre Infolettre",
                    'nine':"S'abonner",
                    'ten':"évaluation gratuite",
                    'eleven':"Consultation gratuite",
                    'twelve':'Contactez-nous',
                    'thirteen':'Prix',
                },
                'placeholder':{
                    'one':'Recherche par ville, quartier, région, adresse ou No Centris.',
                    'two':'Nom Complet',
                    'three':'Courriel',
                    'four':'Téléphone',
                    'five':'Votre courriel',
                    'six':'Votre prénom',
                    'seven':'Votre nom de famille',
                },
                'text': {
                    'one': 'Découvrir',
                    'two': 'Nos statistiques',
                    'three': 'Prix de vente moyen',
                    'four': 'Par Rapport AU Prix Demandé',
                    'five': 'Nombre de jours Moyens',
                    'six': 'Sur le marché',
                    'seven': 'Nombre',
                    'eight': 'De transactions',
                    'nine': 'jours',
                    'ten': 'Rencontrez',
                    'eleven': 'Notre équipe',
                    'twelve': 'LJ Immobilier est une agence qui est en service depuis 2013.',
                    'twelve_b': "Qu'est-ce qui nous différencie des autres? Nous nous efforçons d'être le chef de file de l'industrie immobilière dans la grande région de Montréal en offrant un service inégalé, en tissant la transparence et l'intégrité dans chaque interaction et en adoptant une approche progressive centrée sur l'éducation, tant avec nos clients qu'avec notre équipe. Ceci, associé à notre éthique de travail sans précédent, ne sont que deux des raisons qui nous aident à nous distinguer de nos concurrents.",
                    'thirteen': 'Les Propriétés Populaires',
                    'fourteen': 'Nous faisons des dons à',
                    'fifteen': 'Autisme Montréal',
                    'sixteen': 'Un pourcentage du produit de chaque transaction est versé à Autisme Montréal.',
                    'seventeen': 'Nous avons donné plus de 10 000 dollars en 2023',
                    'eighteen': "Autisme Montréal est un lieu qui inspire, rassemble, porte l'espoir, favorise l'épanouissement et la solidarité sociale.",
                    'nineteen': 'Les témoignages',
                    'twenty': 'De nos clients',
                    'twenty_one': 'Visionnez nos',
                    'twenty_two': 'Dernières vidéos',
                    'twenty_three': 'Nos propriétés vendues',
                    'twenty_four': 'Champs obligatoires',
                    'twenty_five': 'Politique de confidentialité',
                    'twenty_six': 'Tous droits réservés, Columba Technology',
                    'twenty_seven': 'Avis sur les cookies',
                    'twenty_eight': 'Nous utilisons des cookies pour vous offrir la meilleure expérience possible sur notre site Web.',
                    'twenty_nine': "En continuant à naviguer, vous acceptez l'utilisation de cookies sur notre site Web. Pour en savoir plus",
                    'thirty': 'cliquez ici',
                    'thirty_one': "C'est compris",
                    'thirty_two': "En tant que courtiers experts en immobilier, nous fournissons des résultats exceptionnels.",
                    'thirty_three': "Notre prix de vente moyen est l'un des plus élevés du marché, nos biens se vendent plus rapidement et nous avons réalisé de nombreuses transactions avec succès.",
                    'thirty_four': "Faites-nous confiance pour une expérience immobilière transparente et profitable.",
                }
            },
            'menu':{
                'name':{
                    'one':'Propriétés',
                    'two':'Notre Équipe',
                    'three':'Acheter ou Vendre',
                    'four':'Notre Calculateur',
                    'five':'Vidéos',
                    'six':'Blogue',
                    'seven':'Contact',
                },
                'url':{
                    'one':'proprietes',
                    'two':'courtier-immobilier',
                    'three':'travailler-avec-nous',
                    'four':'',
                    'five':'media',
                    'six':'https://blog.ljrealties.com/',
                    'seven':'contact-courtier-immobilier',
                    'eight':'https://41nbopg8umd.typeform.com/to/k4c7H9i3',
                },
            },
            'properties':{
                'text': {
                    'one':"Mode d'affichage",
                    'two':'Liste',
                    'three':'Mosaïque',
                }
            },
            'videos':{
                'title':{
                    'one':'Nos',
                    'two':'Vidéos',
                    'three':'Toutes',
                    'four':'Shorts',
                    'five':'Vidéos',
                },
                'button':{
                    'one':'Visionnez',
                }
            },
            'contact':{
                'title':{
                    'one':'Contactez-',
                    'two':'Nous',
                    'three':'Réalisons vos rêves immobiliers!',
                },
                'button':{
                    'one':'Contactez-Nous',
                    'two':'Planifiez un appel avec nous',
                },
                'text': {
                    'one':'Veuillez remplir ce formulaire et',
                    'two':'Nous vous contacterons dès que possible',
                    'three':'Prénom',
                    'four':' Nom de famille',
                    'five':'Courriel',
                    'six':'Téléphone',
                    'seven':'Commentaires',
                    'eight':'Champs obligatoires',
                    'nine':'Nos coordonnées',
                    'ten':'Appelez-nous',
                    'eleven':'Nous sommes ouverts du lundi au vendredi',
                    'twelve':'Suivez-nous',
                    'thirteen': 'Étapes',
                    'fourteen': 'Suivantes',
                    'fifteen': "Acheter ou vendre une maison dans un marché en pleine effervescence n'est pas facile, mais avec la bonne équipe, vous économiserez du temps et de l'argent.",
                    'sixteen': "Si vous souhaitez analyser des opportunités spécifiques, élaborer un plan d'action et/ou obtenir des réponses à vos questions, l'étape suivante serait d'organiser un appel de stratégies pour l'achat ou la vente d'un bien immobilier.",
                    'seventeen': "La prochaine étape serait de planifier un court appel stratégique pour les acheteurs."
                }
            },
            'privacy':{
                'title':{
                    'one':'Politique',
                    'two':'De Confidentialité',
                },
                'url':'politique-confidentialite',
            },
            'team':{
                'title':{
                    'one':'Vos courtiers',
                    'two':'Immobiliers de confiance',
                    'three': 'Rencontrez notre équipe',
                },
                'button':{
                    'one':'Lire la Bio',
                },
                'text': {
                    'one':'Fondateur et courtier immobilier agréé DA',
                    'two':'Directrice de bureau et Courtier Immobilier Résidentiel',
                    'three':'Courtier Immobilier Résidentiel',
                    'four':'Courtier Immobilier Résidentiel',
                    'five':'Directrice du Marketing',
                    'six':'Coordonnatrice des inscriptionsr',
                    'seven':'Coordonnatrice des transactions',
                    'eight':'Recherche Courtier immobilier',
                }
            },
            'work':{
                'title':{
                    'one':'Travaillez',
                    'two':'Avec Nous',
                    'three':'Acheter ou',
                    'four':'Vendre',
                },
                'button':{
                    'one':"Télécharger la brochure de l'acheteur",
                    'two':'Télécharger la brochure du vendeur',
                    'three':'Contactez-nous',
                    'four':'Télécharger',
                    'five':'Soumettre',
                    'six':"Réservez une consultation d'acheteurs",
                    'seven':"Téléchargez notre guide d'achat",
                    'eight':'Obtenez une évaluation gratuite de votre logement',
                    'nine':'Téléchargez notre guide du vendeur',
                    'ten':'Réservez un appel avec nous',
                },
                'text': {
                    'one':'Je Veux',
                    'two':'Acheter',
                    'three':'Je veux',
                    'four':'Vendre',
                    'five':"Il y a de nombreuses étapes à franchir pour passer de votre situation actuelle à la possession d'une nouvelle maison.",
                    'six':"La vente de votre maison peut vous sembler être un casse-tête mais ne vous inquiétez pas, car nous serons là pour vous aider tout au long du processus. Comptez sur les connaissances approfondies de notre équipe en matière d'immobilier et de finance afin de vous garantir une vente réussie et sans heurts.",
                    'seven':'Aidez-nous à donner',
                    'eight':'Vie à votre projet immobilier',
                    'nine':'Veuillez remplir le formulaire pour afficher le lien de téléchargement',
                    'ten':'Notre expérience garantit votre succès',
                    'eleven':"C'est là que les connaissances et l'expérience entrent en jeu.", 
                    'twelve':"Ne vous inquiétez pas, nous serons là pour vous guider tout au long du processus et vous aider à trouver une propriété qui répond à vos besoins.",
                    'thirteen':"Il s'agit notamment d'être présent lors de toutes les visites, de vous conseiller lors des négociations d'achat, de l'inspection préalable à l'achat, ainsi que du financement afin de conclure l'achat. Toutes ces étapes peuvent sembler insurmontables, mais avec notre aide, vous vous retrouverez dans votre nouvelle maison avant même de vous en rendre compte !",
                    'fourteen':"Visites accompagnées",
                    'fifteen':"Nous serons présents lors de toutes les visites, ce qui vous permettra de bénéficier de conseils d'experts à chaque étape du processus.",
                    'sixteen':"Aide à la négociation",
                    'seventeen':"Notre équipe vous conseillera tout au long des négociations d'achat et vous aidera à obtenir la meilleure offre.",
                    'eighteen':"NSPECTION AVANT L’ACHAT",
                    'nineteen':"Nous vous assisterons lors de l'inspection préalable à l'achat afin de nous assurer que votre future maison répond à toutes vos attentes.",  
                    'twenty':"Aide au financement",
                    'twenty_one':"Nous vous aiderons à obtenir un financement en vous guidant vers les meilleures options pour vos besoins.", 
                    'twenty_two':"Achèvement de l'achat",
                    'twenty_three':"Enfin, nous vous accompagnerons jusqu'à la fin de l'achat, en veillant à ce que tout se passe bien.",
                    'twenty_four':"Vous pouvez compter sur les connaissances approfondies de notre équipe en matière d'immobilier et de finances, pour vous aider dans les vérifications, les évaluations, le marketing, etc.",
                    'twenty_five':'Consultation initiale',
                    'twenty_six':"Nous discuterons de vos objectifs et évaluerons la valeur de votre maison.",
                    'twenty_seven':'Vérification et évaluation',
                    'twenty_eight':'Vous pourrez bénéficier de notre expertise pour effectuer des vérifications approfondies et des évaluations précises.',
                    'twenty_nine':'Stratégies de marketing',
                    'thirty':'Nous élaborerons et mettrons en œuvre un plan de marketing efficace pour vous.',
                    'thirty_one':'Visites et journées portes ouvertes',
                    'thirty_two':'Nous organiserons et gérerons les visites de biens immobiliers.',
                    'thirty_three':'Négociations',
                    'thirty_four':'Nous vous guiderons dans les offres et les négociations.',
                    'thirty_five':'Fermeture',
                    'thirty_six':'Nous vous aiderons à franchir les dernières étapes de la vente.',
                    'thirty_seven':'Étapes',
                    'thirty_eight':'Suivantes',
                    'thirty_nine':"Acheter ou vendre une maison dans un marché en pleine effervescence n'est pas facile,",
                    'forty':"mais avec la bonne équipe, vous économiserez du temps et de l'argent.",
                    'forty_one':"Si vous souhaitez analyser des opportunités spécifiques, élaborer un plan d'action et/ou obtenir",
                    'forty_two':"des réponses à vos questions, l'étape suivante serait d'organiser un appel de stratégies pour l'achat ou la vente d'un bien immobilier.",
                },
                'placeholder':{
                    'one':'Nom et prénom',
                    'two':'Courriel',
                    'three':'Téléphone',
                },
            },
            'blog':{
                'button':{
                    'one':'Se connecter',
                    'two':'Pas de compte ?',
                    'three':'Inscrivez-vous.',
                    'four':'Créez votre compte',
                    'five':'Soumettre un commentaire',
                },
                'placeholder':{
                    'one':'Courriel',
                    'two': 'Confirmer le courrier',
                    'three': 'Mot de passe',
                    'four': 'Confirmer le mot de passe',
                },
                'error':{
                    'one':'Les courriels ne correspondent pas.',
                    'two': 'Les mots de passe ne correspondent pas.',
                    'three': 'Le mot de passe doit comporter au moins 8 caractères, des lettres, des chiffres et un caractère spécial.',
                    'four': 'Le commentaire ne peut pas être vide',
                },
                'text':{
                    'one':'Commentaires',
                }
            },
        },
    },
}
