# Generated by Django 4.2.11 on 2024-05-11 20:04

import apps.parametrization.files_path
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('cellphone', models.CharField(blank=True, max_length=15)),
                ('telephone', models.CharField(blank=True, max_length=15)),
                ('photo', models.ImageField(blank=True, default='companys/photos/no_photo.png', upload_to=apps.parametrization.files_path.company_path)),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'Crear Empresas',
                'db_table': 'company',
                'ordering': ['name'],
            },
        ),
    ]
