# Generated by Django 3.2.25 on 2024-08-02 17:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('cellphone', models.CharField(blank=True, max_length=15)),
                ('telephone', models.CharField(blank=True, max_length=15)),
            ],
            options={
                'verbose_name': 'admin_company',
                'verbose_name_plural': 'Crear Empresas',
                'db_table': 'admin_company',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TypeUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('english', models.CharField(max_length=60)),
                ('french', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'admin_type_user',
                'db_table': 'admin_type_user',
            },
        ),
    ]
